name: Ruby

on:
  push:
    branches: [ master]
    pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Set up Ruby
    uses: ruby/setup-ruby@1
    with:
      ruby-version: 2.7.1

  - name: Cache Ruby Gems
    uses: actions/cache@v2
    with:
      path: vendor/bundle
      key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      restore-keys: |
        ${{ runner.os }}-gems-

  - name: Bundle Install
    run: |
      bundle config path vendor/bundle
      bundle install --jobs 4 --retry 3
  - name: Run Tests
    env:
      RAILS_ENV: test
      DISABLE_SPRING: 1
    run: |
      bundle exec rspec
